### ISSUE TITLE
Unable to setup kubeseal-webgui using provided helm chart

### ISSUE THREAD

**Issue by Shivam0609** [Jaydee94/kubeseal-webgui#138]
I am trying to install helm chart for `kubeseal-webgui`  on k8s cluster provided in docker desktop.

followed steps mentioned in `readme`.  Below is my  `values.yaml` file.

I do have one doubt regarding `api.url` is this default value okay ? Do we need to  expose this  endpoint ourself or is it taken care by helm chart ?

```yaml
replicaCount: 1

annotations: {}

api:
  # The value of api.url should be set to the public-accessible http endpoint (ingress url or OpenShift route).
  # api.url will be generated into config.json ConfigMap of the UI. This statically served JSON file
  # is used by the UI to locate the API.
  url: http://localhost:8080
  image:
    repository: kubesealwebgui/api
    tag: 3.1.0
  environment: {}
ui:
  image:
    repository: kubesealwebgui/ui
    tag: 3.1.0
image:
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

# Optionally setup a display name for your kubeseal-webgui instance.
displayName: ""

# Set this value to false if you already have a default serviceaccount who is allowed to list namespaces.
serviceaccount:
  create: false

# Setup resources for the pod
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 20m
    memory: 256Mi

# Optionally use a OpenShift-Route
# If 'hostname' is an empty string (""), OpenShift will create a hostname for you.
route:
  enabled: false
  hostname: ""
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None

sealedSecrets:
  autoFetchCert: false
  controllerName: sealed-secrets-controller
  controllerNamespace: kube-system
  ## Public Certificate of your Sealed-Secrets Controller.
  ## Login to your cluster with kubectl.
  ## Run kubeseal --fetch-cert --controller-name <your-sealed-secrets-controller> --controller-namespace <sealed-secrets-controller-namespace>
  ## Paste Cert as multiline YAML
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIEzDCCArSgAwIBAgIQTu139c2EK+zC/rwU4DxhYzANBgkqhkiG9w0BAQsFADAA
    ............................................
    ...........................................
    -----END CERTIFICATE-----
```

Getting below error on UI and not able to list any namespace , I have also fetched the cert.pem from kubeseal-controller and provided same in values file as mentioned in the project. I have no clue what is wrong in here.

![image](https://user-images.githubusercontent.com/27969092/180616583-91d6f058-ccc6-4e6d-8b9c-e4a9df8f740c.png)
