### ISSUE TITLE
Missing nodeSelector, tolerations and affinity configuration

### ISSUE THREAD

**Issue by cedvan** [Jaydee94/kubeseal-webgui#193]
Hi,

Manage Pod execution is a must have to control cluster.

#### Add an configuration to configure Pod Template

default *values.yaml*
```yaml
nodeSelector: {}
tolerations: []
affinity: {}
```

*template/deployment.yaml*
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeseal-webgui.fullname" . }}
  ....
spec:
  ...
  template:
    ...
    spec:
      nodeSelector: {{ .Values.nodeSelector }}
      tolerations: {{ .Values.tolerations }}
      affinity: {{ .Values.affinity }}
```

#### Sample result configuration

*values.yaml*
```yaml
displayName: 'Kubeseal Secret'
replicaCount: 2
tolerations:
    - key: "my-taint-key"
      operator: Equal
      value: my-taint-value
      effect: NoSchedule
nodeSelector:
    my-label-key: my-label-value
affinity:
    nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                  - matchExpressions:
                      - key: my-second-label-key
                        operator: In
                        values:
                            - my-second-label-value
```

**Comment by Jaydee94** [comment]
Hey @cedvan.
We just released version 4.0.3. 

Your requested changes are included in the chart version 4.0.3.

Best regards.

**Comment by cedvan** [comment]
Great ! Thank you :)

**Comment by cedvan** [comment]
Hum, tolerations must be an `array` (`[]`) and affinity an `object` (`{}`), you reversed ;)

**Comment by Jaydee94** [comment]
@cedvan Damn it 🫣
I will fix this later this day. 😄

**Comment by Jaydee94** [comment]
@cedvan I just looked into the source code.
![image](https://user-images.githubusercontent.com/55805868/201966090-e1f71574-2bc7-42f3-8a24-78fdf860795b.png)
Am i wrong or isn't already configured as expected?

**Comment by Jaydee94** [comment]
@cedvan Ah my mistake. Only the README was wrong. The values.yaml already has the expected types.

**Comment by cedvan** [comment]
Hum, I tried new version, and my argoCD declare this error

**Comment by Jaydee94** [comment]
Version 4.0.3?

**Comment by cedvan** [comment]
Helm build log : 
```txt
...kubeseal-webgui/templates/deployment.yaml: error converting YAML to JSON: yaml: line 28
```

*values.yaml*
```
    tolerations:
        - key: "sample-domain.com/node-role"
          operator: Equal
          value: service
          effect: NoSchedule
    nodeSelector:
        sample-domain.com/node-role: service
```
