### ISSUE TITLE
Error while listing namespaces

### ISSUE THREAD

**Issue by vojtechmares** [Jaydee94/kubeseal-webgui#276]
Hi, I've not labeled this as a bug, since I'm not 100% sure its a bug or just my misconfiguration.

I've deployed the kubeseal-webgui using the provided Helm chart with ArgoCD.

The values are as follow:

```yaml
ingress:
  enabled: true
  hostname: kubeseal.[REDACTED]
  ingressClassName: nginx

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production

  tls:
    enabled: true
    secretName: kubeseal-ui-ingress-tls

sealedSecrets:
  controllerNamespace: kube-system
  controllerName: sealed-secrets-controller
  autoFetchCert: true
```

Since `customServiceAccountName` is not defined, the default SA is created, including CR and CRB. I've validated that the resources exist via _kubectl_. Yet, the UI is still showing an error, that it failed to fetch namespaces (see attached sreenshot). 

This is a blocking issue and I'm unable to seal any secrets unfortunately.

<img width="1225" alt="Image" src="https://github.com/user-attachments/assets/bd541d2f-9982-4610-80a1-22354f84698b" />

Did I miss some configuration option or something? I do not see the error and ChatGPT was no help at all (unsurprisingly). Thanks!
